FROM python:3-alpine

ENV NO_GROUPS=1

ADD ./ /opt/cda_exc

RUN apk -U add --no-cache bash \
    && chmod +x /opt/cda_exc/run_cda_groups.sh \
    && pip install ConfigArgParse \ 
    && pip install pytz
WORKDIR /opt/cda_exc
VOLUME /data
CMD ["bash"]
EXPOSE 9001 9002 9003 9004 9005 9006 9007 9008 9009 9010
