FROM python:3.6-alpine

ADD ./ /opt/cda_exc

RUN apk -U add --no-cache bash \
    && pip install ConfigArgParse \ 
    && pip install pytz

WORKDIR /opt/cda_exc
VOLUME /data
ENTRYPOINT ./run_cda_groups.sh "$NUM_GROUPS"
EXPOSE 9000-9010
